import { Inter } from "next/font/google";
import "../styles/globals.css";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontInter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${fontInter.variable} antialiased`}>
        {children}

        <Footer />
      </body>
    </html>
  );
}
